export const PROTOCOL_VERSION = 1 as const

export const DEFAULT_SERVICE_PORT = 53_317
export const MIN_SERVICE_PORT = 1_024
export const MAX_SERVICE_PORT = 65_535

export const MAX_TEXT_BYTES = 64 * 1_024
export const MAX_WEBSOCKET_MESSAGE_BYTES = 128 * 1_024
export const MAX_FILE_SIZE_BYTES = 2 * 1_024 * 1_024 * 1_024
export const MAX_FILES_PER_TRANSFER = 20

export const HEARTBEAT_INTERVAL_MS = 10_000
export const HEARTBEAT_TIMEOUT_MS = 30_000
export const CONNECTION_TIMEOUT_MS = 10_000
export const TRANSFER_TIMEOUT_MS = 5 * 60_000
export const FILE_SELECTION_TOKEN_TTL_MS = 10 * 60_000
export const DIRECTORY_SELECTION_TOKEN_TTL_MS = 60_000
export const TRANSFER_PROGRESS_UPDATE_INTERVAL_MS = 100
export const TRANSFER_PROGRESS_MESSAGE_INTERVAL_MS = 500
export const TRANSFER_IDLE_TIMEOUT_MS = 30_000
export const MESSAGE_CLOCK_SKEW_MS = 5 * 60_000

export const RATE_LIMIT_WINDOW_MS = 60_000
export const MAX_HTTP_REQUESTS_PER_WINDOW = 120
export const MAX_WEBSOCKET_UPGRADES_PER_WINDOW = 10
export const MAX_WEBSOCKET_MESSAGES_PER_WINDOW = 600
export const MAX_RATE_LIMIT_IDENTITIES = 1_024
export const MAX_SERVER_CONNECTIONS = 64

export const TEMPORARY_FILE_MAX_AGE_MS = 24 * 60 * 60_000
export const DISK_SPACE_RESERVE_BYTES = 16 * 1_024 * 1_024
export const FILE_OPERATION_RETRY_COUNT = 3
export const FILE_OPERATION_RETRY_DELAY_MS = 100
export const MAX_IN_MEMORY_TRANSFER_TASKS = 100
export const TRANSFER_ID_RETENTION_MS = 24 * 60 * 60_000
export const MAX_AUTHORIZED_FILE_SELECTIONS = 100
export const MAX_AUTHORIZED_DIRECTORIES = 20

export const MESSAGE_DEDUPLICATION_LIMIT = 2_000
export const MESSAGE_DEDUPLICATION_TTL_MS = 10 * 60_000

export const DEFAULT_HISTORY_LIMIT = 1_000
export const MIN_HISTORY_LIMIT = 100
export const MAX_HISTORY_LIMIT = 10_000
export const MAX_RECENT_DEVICES = 20
export const MAX_HISTORY_TEXT_PREVIEW_LENGTH = 500
